branches:
  only:
    - master

image: Visual Studio 2019

environment:
  GOPATH: c:\gopath

init:
  - SET PATH=%GOPATH%\bin;%PATH%
  - git config --global core.autocrlf input

install:
  - go version
  - go env
  - mkdir %GOPATH%
  - go get -u github.com/tischda/go2xunit

build_script:
  - for /f "delims=" %%a in ('git describe --tags') do @set version=%%a
  - ps: Update-AppveyorBuild -Version $env:version
  - go build -mod vendor -ldflags=all="-X main.version=%version% -s -w"

test_script:
  - webloc.exe -version
  - go test -v -cover
  - dir %GOPATH%\bin\go2xunit.exe
  - go test -v | %GOPATH%\bin\go2xunit.exe -xunitnet > xunit-report.xml
  - webloc.exe data

artifacts:
  - path: webloc.exe
    name: Webloc

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
